name: sieuthimini
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Gói cần thiết khi chạy ứng dụng
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.7+4
  json_serializable: ^6.7.1
  fl_chart: any
  qr_flutter: ^4.0.0  # <-- thêm qr_flutter tại đây
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Gói cần thiết khi phát triển
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  intl: ^0.18.1
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Khai báo assets
  assets:
    - assets/images/